# User root password root
version: '3.1'

services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todolist
      POSTGRES_USER: user1
    ports:
      - '5432:5432'
    expose: 
      - '5432'